version: '3.9'
services:
  readme.users.mongo:
    image: mongo:4.4
    restart: always
    container_name: ${MONGO_DB}.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - readme.mongo.users:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:${MONGO_PORT}/${MONGO_DB} --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.users.mongo.ui:
    image: mongo-express:latest
    restart: always
    container_name: ${MONGO_DB}.mongo.ui
    ports:
      - ${MONGO_UI_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_UI_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_UI_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_DB}.mongo:${MONGO_PORT}/

volumes:
  readme.mongo.users:
